### ISSUE TITLE
Error parsing menu (first call only)

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/las2peer-Mensa-Service#3]
First call to any menu fails: 

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -12
        at java.lang.String.substring(Unknown Source)
        at i5.las2peer.services.mensaService.MensaService.getMensaMenu(MensaService.java:164)
        at i5.las2peer.services.mensaService.MensaService.saveDishesToIndex(MensaService.java:633)
        at i5.las2peer.services.mensaService.MensaService.updateDishes(MensaService.java:612)
        at i5.las2peer.services.mensaService.PrematchingRequestFilter.filter(PrematchingRequestFilter.java:20)
```

**Comment by lakhoune** [comment]
@AlexanderNeumann I think we can close this issue 🙂
